name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to server
        env:
          API_KEY: ${{ secrets.ACCOUNTS_JSON }}
        run: |
          echo "Deploying with API_KEY: $API_KEY"
